app/models/user.py
from ..extensions import db


class User(db.Model):
    __tablename__='appuser'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20))

app/__init__.py
from flask import Flask
from .extensions import bootstrap, db, migrate
from .routes.controller import controller

def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite3'
    app.config['SQLALCHEMY_TRACK_NOTIFICATIONS'] = False
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)
    migrate.init_app(app, db)
    bootstrap.init_app(app)

    app.register_blueprint(controller)

    return app

app/app.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap

app = Flask(__name__)

Bootstrap(app)

@app.route('/')
def index():
    return(render_template('index.html'))

@app.route('/trends')
def trends():
    return(render_template('trends.html'))


@app.route('/medicines')
def medicines():
    return(render_template('medicines.html'))


@app.route('/reports')
def reports():
    return(render_template('reports.html'))


@app.route('/settings')
def settings():
    return(render_template('settings.html'))


@app.route('/booktest')
def booktest():
    return(render_template('booktest.html'))
    

@app.route('/contact-us')
def contact():
    return(render_template('contact.html'))


if __name__ == '__main__':
    app.run(host='0.0.0.0')

app/routes/controller.py
import imp
from flask import Flask, render_template
from flask import Blueprint
from ..extensions import db
from ..models.user import User

controller = Blueprint('controller', __name__)

@controller.route('/user/<name>')
def create_user(name):
    user = User(name=name)
    db.session.add(user)
    db.session.commit()
    return 'User create successfully!!'

@controller.route('/')
def index():
    return(render_template('index.html'))

@controller.route('/trends')
def trends():
    return(render_template('trends.html'))


@controller.route('/medicines')
def medicines():
    return(render_template('medicines.html'))


@controller.route('/reports')
def reports():
    return(render_template('reports.html'))


@controller.route('/settings')
def settings():
    return(render_template('settings.html'))


@controller.route('/booktest')
def booktest():
    return(render_template('booktest.html'))
    

@controller.route('/contact-us')
def contact():
    return(render_template('contact.html'))

app/templates/booktest.html
{% extends "index.html" %}

{% block content %}
<div class="container">
    <blockquote class="blockquote text-center">
        <p class="mb-0"><h1>Book Your Tests</h1></p>
        <footer class="blockquote-footer">Coming Soon <cite title="Source Title"></cite></footer>
      </blockquote>
</div>
{% endblock %}

app/templates/contact.html
{% extends "index.html" %}
{% block content %}
<div class="container contact-form">
    <div class="contact-image">
        <img src="{{ url_for('static', filename = 'rocket_contact.png') }}" alt="rocket_contact"/>
    </div>
    <form method="post">
        <h3>Drop Us a Message</h3>
       <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="text" name="txtName" class="form-control" placeholder="Your Name *" value="" />
                </div>
                <div class="form-group">
                    <input type="text" name="txtEmail" class="form-control" placeholder="Your Email *" value="" />
                </div>
                <div class="form-group">
                    <input type="text" name="txtPhone" class="form-control" placeholder="Your Phone Number *" value="" />
                </div>
                <div class="form-group">
                    <input type="submit" name="btnSubmit" class="btn btn-success" value="Send Message" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <textarea name="txtMsg" class="form-control" placeholder="Your Message *" style="width: 100%; height: 150px;"></textarea>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/templates/index.html
{% extends "bootstrap/base.html" %}

{% block head %}
{{ super() }}

{% endblock %}

{% block navbar %}

<div class="navbar" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('controller.index') }}">Home</a></li>
            <li><a href="{{ url_for('controller.booktest') }}">Book Test</a></li>
            <li><a href="{{ url_for('controller.medicines') }}">Medicines</a></li>
            <li><a href="{{ url_for('controller.trends') }}">Health Trends</a></li>
            <li><a href="{{ url_for('controller.settings') }}">Settings</a></li>
            <li><a href="{{ url_for('controller.reports') }}">Reports</a></li>
            <li><a href="{{ url_for('controller.contact') }}">Contact Us</a></li>
        </ul>
       
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">

                    Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a>Change Password</a></li>
                    <li><a>Admin</a></li>
                    <li><a>Logout</a></li>
                </ul>
            </li>

        </ul>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <blockquote class="blockquote text-center">
        <p class="mb-0"><h1>Medidesk App</h1></p>
        <footer class="blockquote-footer">Coming Soon <cite title="Source Title"></cite></footer>
      </blockquote>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}

{% endblock %}

app/templates/medicines.html
{% extends "index.html" %}

{% block content %}
<div class="container">
    <blockquote class="blockquote text-center">
        <p class="mb-0"><h1>Medicines</h1></p>
        <footer class="blockquote-footer">Coming Soon <cite title="Source Title"></cite></footer>
      </blockquote>
</div>
{% endblock %}

app/templates/reports.html
{% extends "index.html" %}

{% block content %}
<div class="container">
    <blockquote class="blockquote text-center">
        <p class="mb-0"><h1>Reports</h1></p>
        <footer class="blockquote-footer">Coming Soon <cite title="Source Title"></cite></footer>
      </blockquote>
</div>
{% endblock %}

app/templates/settings.html
{% extends "index.html" %}

{% block content %}
<div class="container">
    <blockquote class="blockquote text-center">
        <p class="mb-0"><h1>Settings</h1></p>
        <footer class="blockquote-footer">Coming Soon <cite title="Source Title"></cite></footer>
      </blockquote>
</div>
{% endblock %}

app/templates/trends.html
{% extends "index.html" %}

{% block content %}
<div class="container">
    <blockquote class="blockquote text-center">
        <p class="mb-0"><h1>Your Health Trends</h1></p>
        <footer class="blockquote-footer">Coming Soon <cite title="Source Title"></cite></footer>
      </blockquote>
</div>
{% endblock %}